---
title: "Skills Course"
author: "Mvdp"
date: "2026-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
#Packages
#Packages
setwd("C:/Users/vdpma/OneDrive/Desktop/Actual Data")


library(ggplot2)
library(tidyr)
library(tidyverse)
library(dplyr)
library(ggsignif)
```


```{r}
#Leaf Scans
#Adjusting the mean values to account for background effects.
data1 <- read.csv("Actual Data/FDG/THEACTUALRESULTS.csv")
summary(data1)
length(data1$Value)
adjusted <- vector(mode = "numeric", length = length(data1$Value))
for (i in 1:length(data1$Value)){
  adjusted[i] <- data1[i, ]$Value - 885.013
  }
adjusted
data1 <- data1 %>% mutate(adjusted_results = adjusted) 
head(data1)
View(data1)

#Renaming The Rows


data1$X <- as.character(data1$X)
data1$X[1]<- "EV1"
data1$X[2]<- "Gsn1"
data1$X[3]<- "FDG1"
data1$X[4]<- "EV2"
data1$X[5] <- "Gsn2"
data1$X[6]<- "FDG2"
data1$X[7]<- "EV3"
data1$X[8]<- "Gsn3"
data1$X[9]<- "FDG3"
data1$X[10]<- "EV4"
data1$X[11]<- "Gsn4"
data1$X[12]<- "FDG4"
data1$X[13]<- "EV5"
data1$X[14]<- "Gsn5"
data1$X[15]<- "FDG5"

#Finding the means for each group. 
EV <- data1 %>% filter(grepl("EV", X))
meanEV <- mean(EV$adjusted_results)
meanEV

Gsn <- data1 %>% filter(grepl("Gsn", X))
meanGsn <- mean(Gsn$adjusted_results)
meanGsn

FDG <- data1 %>% filter(grepl("FDG", X))
meanFDG <- mean(FDG$adjusted_results)
meanFDG

```


```{r}
#H0: there is no significant difference in the level of fluorescence between the empty vector- and the glycosyrin-infiltrated leaf sections.
#HA: there is a significant decrease in fluorescence between the empty vector- and glycosyrin-infiltrated leaf sections.

#Pairwise t-test.
dataChanged <- data1 %>% mutate(Group = case_when(str_detect(X, "EV") ~ "EV",
                                                  str_detect(X, "Gsn") ~ "Gsn",
                                                  str_detect(X, "FDG") ~ "FDG"))


dataChanged <- dataChanged %>% group_by(Group)
View(dataChanged)

#Calculating mean, standard error and standard deviation.
dataChanged2 <- dataChanged %>% summarise(stanDev <- sd(adjusted_results, na.rm = TRUE),
                                          n = n(),
                                        se_value= sd(adjusted_results, na.rm = TRUE)/sqrt(n), 
                                        mean_value = mean(adjusted_results))
View(dataChanged2)
View(dataChanged)

dataPlant <- dataChanged %>%mutate(plant = case_when(str_detect(X, "1")~ "1",
                                                     str_detect(X, "2") ~ "2",
                                                     str_detect(X, "3") ~ "3",
                                                     str_detect(X, "4") ~ "4",
                                                     str_detect(X, "5") ~ "5"))
View(dataPlant)
#Quick ANOVA:
anovaFDG <- lm(adjusted_results ~ Group, data = dataPlant)
summary(anovaFDG) #The p-value = 0.01625, so Group explains a significant amount of variation in the relative levels of FDG. (R^2 = 0.4967). 
anovaFDGPlant <- lm(adjusted_results ~ Group + plant, data = dataPlant)
summary(anovaFDGPlant) #When the plant is also taken into account, R^2 = 0.8311, which indicates that much of the variation in relative FDG levels is due to different plants, which were of different sizes, and leaves were of different ages. Some plants would have been wounded more in the process of agroinfiltration. 

#Checking assumptions:
EVleaf <- dataChanged %>% filter(Group == "EV")
Gsnleaf <- dataChanged %>% filter(Group == "Gsn")
FDGleaf <- dataChanged %>% filter(Group == "FDG")
shapiro.test(EVleaf$adjusted_results)
shapiro.test(Gsnleaf$adjusted_results)
shapiro.test(FDGleaf$adjusted_results)#The p-values are all above 0.05, so the distribution of the data is not significantly non-normal.
#Homogeneity of variances:
bartlett <- bartlett.test(adjusted_results ~ Group, data = dataChanged)
bartlett #There is significant variation in variances as the p-value is less than 0.05. #This should be tolerated as the sample sizes are all the same, and it is logical to stick with pool.sd = TRUE because the sample sizes are relatively small.
#Pairwise t test:
t <- with(dataChanged, pairwise.t.test(adjusted_results, Group, p.adj = "holm"))
t #The p-values for the tests between FDG alone and Gsn and EV and Gsn are both < 0.05, so there is a significant difference between the relative levels of FDG in Gsn and the controls. The p-value for EV and FDG > 0.05 and is almost 1, as expected.
#Tukey test
fdganova <- aov(anovaFDG)
tukey <- TukeyHSD(fdganova)
tukey

```

Graph:
```{r}
#Graphing the results from the Typhoon scanning.
#Creating a theme to be used throughout the graphs:
my_theme <- function(){
  theme_bw() +
    theme(
      axis.text = element_text(size = 12),
      axis.title = element_text(size = 14, face = "bold"),
      plot.title = element_text(size = 15, face = "bold", hjust = 0.5),
      plot.subtitle = element_text(size = 14, hjust = 0.5),
      plot.caption = element_text(size = 10, face = "italic"), 
      panel.grid = element_blank(),
     legend.position = "none"
    )
}

#new_palette <- c("#500067", "#6D00FF", "#C153FF")
#names(new_palette) <- levels(dataChanged2$Group)

(typhoon_box <- ggplot(dataChanged2, aes(x = Group, y = mean_value)) +
   geom_bar(position = "dodge", stat = "identity", aes(fill = Group)) +
   geom_errorbar(aes(ymin = (mean_value - (2*se_value)),
                     ymax = (mean_value + (2*se_value)),
                     width = 0.2),
                     position = position_dodge(0.7)) +
  xlab("\nTreatment") +
  ylab("Relative FDG (16-bit Greyscale)\n") +  #Average pixel intensity measured using ImageJ is a proxy for fluorescence.
  scale_y_continuous(limits = c(0, 25000)) +
    labs(title = "Glycosyrin Decreases Relative Levels of Fluorescein di-β-D-Galactopyranoside (FDG)",
         subtitle = "Relative FDG 3dpi with Glycosyrin Treatment (100 nM)\n",
         caption = "Data from analysis of Typhoon scans using ImageJ.") +
    my_theme()+
    scale_fill_manual(values = new_palette,
  name = "Treatment",
  labels = c("Empty Vector (EV)", "FDG Alone", "Glycosyrin (Gsn)")))


ggsave("TyphoonRpurple.png", width = 10, height = 10, dpi = 500)


new_palette <- c("#009C59", "#00F92D", "#184A00")
names(new_palette) <- levels(dataChanged2$Group)


#A version of the graph with the data points included:
(typhoon_box <- ggplot(dataChanged2, aes(x = Group, y = mean_value)) +
   geom_bar(position = "dodge", stat = "identity", aes(fill = Group)) +
   geom_errorbar(aes(ymin = (mean_value - (2*se_value)),
                     ymax = (mean_value + (2*se_value)),
                     width = 0.2),
                     position = position_dodge(0.7)) +
    geom_point(aes(x = Group, y = adjusted_results), dataChanged) +
    annotate("segment", x = 2, xend= 3, y = 29000, yend = 29000, size = 1) +
    annotate("segment", x = 1.2, xend= 3.2, y = 31000, yend = 31000, size = 1) +
    annotate("segment", x = 1.2, xend= 1.2, y = 31000, yend = 30000, size = 1) +
    annotate("segment", x = 3.2, xend= 3.2, y = 31000, yend = 30000, size = 1) +
    annotate("segment", x = 3, xend= 3, y = 29000, yend = 28000, size = 1) +
    annotate("segment", x = 2, xend= 2, y = 29000, yend = 28000, size = 1) +
    annotate("text", x = c(1.5, 2.2, 2.5), y = c(0, 31200, 29200), label = c("", "*", "*"), size = 5) +
  xlab("\nTreatment") +
  ylab("Relative FDG (16-bit Greyscale)\n") +  #Average pixel intensity measured using ImageJ is a proxy for fluorescence.
  scale_y_continuous(limits = c(-70, 31500)) +
    labs(title = "Glycosyrin Inhibits Apoplastic Galactosidases",
         subtitle = expression("Relative FDG Fluorescence (10μM) with" ~italic( Agrobacterium) ~ "(Gsn) 3dpi"),
         caption = "Error Bars = +/-2 Standard Errors") +
    my_theme()+
    scale_fill_manual(values = new_palette) +
    scale_x_discrete(labels = c("EV" = "Empty Vector (EV)", "FDG" = "FDG", "Gsn" = "Glycosyrin")))

ggsave("TyphoonVersion4.png", width = 10, height = 10, dpi = 300)
view(dataChanged)
```

Ponceau:
```{r}
#Lectin Blots
#Confirm the assumption that there is not a significant difference in the level of protein loaded onto the gels.
#HA: for each of the lectin blots, there is a significant increase in binding with glycosyrin relative to the empty vector control. Adjust for the background.
```


```{r}
#Ponceau
#RCAI
#H0: there is no difference in the level of protein between EV and Gsn on the Western blots. 
#A two-sample t-test because there are only two groups, and every sample came from a different plant, so samples are independent and not paired. 
RCAIPon <- read.csv("Actual Data/Lectin Blot/RCAI/RCAIPonceauLongSum4567and8andthesummedonesarebackground.csv")

View(RCAIPon)
background <- sum(RCAIPon$Area[4:8])

adj <- vector(mode = "numeric", length = length(RCAIPon$Area))
for (i in 1:length(RCAIPon$Area)){
  adj[i] <- RCAIPon[i, ]$Area - background
  }


RCAIPonAdj <- RCAIPon %>% mutate(adjArea = adj)
View(RCAIPonAdj)

RCAIPonAdj <- RCAIPonAdj[-c(4, 5, 6, 7, 8), ]
EVPon <- c(RCAIPonAdj$adjArea[1:3])
GsnPon <- c(RCAIPonAdj$adjArea[4:6])
#Checking of assumptions
#Is each sample normally distributed?
shapiro.test(EVPon)
shapiro.test(GsnPon) #The p-values for both are above 0.05, so the distribution of the data is not significantly non-normal.
#Homogeneity of variances:
f <- var.test(EVPon,GsnPon,alternative = "two.sided")
f #The p-value > 0.05, so there is no significant difference in variances.
#T-test:
t <- t.test(EVPon, GsnPon, alternative = "two.sided", var.equal = TRUE)
t
#The p-value (0.0492) is less than 0.05, but only just, so considering 0.05 is an arbitrary threshold I am not too concerned about this result.This could be due to the small puncture in the gel, perhaps.

#Excluding the puncture wound:
row1 <- read.csv("Actual Data/Lectin Blot/RCAI/RCAIPonceauRow1.csv")
View(row1)
EV1 <- c(row1$Area[1:3])
Gsn1 <- c(row1$Area[4:6])
t1 <- t.test(EV1, Gsn1, alternative = "two.sided", var.equal = TRUE)
t1 #p-value = 0.3688.

row2 <- read.csv("Actual Data/Lectin Blot/RCAI/RCAIPonceauRow2.csv")
View(row2)
EV2 <- c(row2$Area[1:3])
Gsn2 <- c(row2$Area[4:6])
t2 <- t.test(EV2, Gsn2, alternative = "two.sided", var.equal = TRUE)
t2 #p-value = 0.4854. 

row3 <- read.csv("Actual Data/Lectin Blot/RCAI/RCAIPonceauRow3.csv")
View(row3)
EV3 <- c(row3$Area[1:3])
Gsn3 <- c(row3$Area[4:6])
t3 <- t.test(EV3, Gsn3, alternative = "two.sided", var.equal = TRUE)
t3 #p-value = 0.5562. 
#For all three of the rows, there was no significant difference between the levels of protein loaded for EV and Gsn lanes, which suggests that the puncture wound was a potential confounder because these bands were spread throughout the gel, avoiding the puncture wound. In summary, the slight difference in protein loading between the EV and Gsn lanes on the RCAI gel can largely be ignored.  

```


```{r}
#Ponceau
#ConA
ConAPon <- read.csv("Actual Data/Lectin Blot/ConA/ConAPonceauLong4isbackgroundSum5and6.csv")

View(ConAPon)
background <- ConAPon$Area[4]
background
ConAPon[5, 2] <- sum(ConAPon$Area[5:6])
View(ConAPon)

adj1 <- vector(mode = "numeric", length = length(ConAPon$Area))
for (i in 1:length(ConAPon$Area)){
  adj1[i] <- ConAPon[i, ]$Area - background
  }


ConAPonAdj <- ConAPon %>% mutate(adjArea1 = adj1)
View(ConAPonAdj)

ConAPonAdj <- ConAPonAdj[-c(4, 6), ]

EVPon1 <- c(ConAPonAdj$adjArea1[1:3])
GsnPon1 <- c(ConAPonAdj$adjArea1[4:6])

#Checking of assumptions
#Is each sample normally distributed?
shapiro.test(EVPon1)
shapiro.test(GsnPon1) #The p-values for both are above 0.05, so the distribution of the data is not significantly non-normal.
#Homogeneity of variances:
f <- var.test(EVPon1,GsnPon1,alternative = "two.sided")
f #The p-value > 0.05, so there is no significant difference in variances.
#T-test:
t <- t.test(EVPon1, GsnPon1, alternative = "two.sided", var.equal = TRUE)
t
#The p-value (0.7867) > 0.05, so the difference between mean protein loading is not significant.
```

Lectin Blots:
```{r}
#Lectin blot
#RCAI
#Two sample t-test because each lane represents the apoplastic proteome from a plant infiltrated with either EV or Gsn, so each sample is independent. 
WestRCAI <- read.csv("Actual Data/RCAILong.csv")
View(WestRCAI)

background <- WestRCAI$Area[4]
background


adjWest <- vector(mode = "numeric", length = length(WestRCAI$Area))
for (i in 1:length(WestRCAI$Area)){
  adjWest[i] <- WestRCAI[i, ]$Area - background
}

WestRCAIAdj <- WestRCAI %>% mutate(adjAreaWest = adjWest)
WestRCAIAdj <- WestRCAIAdj[-4, ]
View(WestRCAIAdj)

RCAIEV <- WestRCAIAdj$adjAreaWest[1:3]
RCAIGsn <- WestRCAIAdj$adjAreaWest[4:6]

#Assumptions:
shapiro.test(RCAIEV)
shapiro.test(RCAIGsn)#The p-values are 0.3907 and 0.3318, so the data is not significantly non-normal.

fRCAI <- var.test(RCAIEV,RCAIGsn, alternative = "two.sided")
fRCAI 
#F = 0.01527, num df = 2, denom df = 2, p-value = 0.03008. the variances were not equal, so I used Welch's t-test. 

#T-test:
tRCAI <- t.test(RCAIEV, RCAIGsn, alternative = "two.sided", var.equal = FALSE)
tRCAI
#t = -1.6853, df = 2.0611, p-value = 0.2303.

```


```{r}
#Lectin Blot
#ConA
#Using all the data:
WestConA <- read.csv("Actual Data/ConALong.csv")
View(WestConA)

background <- WestConA$Area[4]
background


WestConA <- WestConA[-4, ]

adjWestConA <- vector(mode = "numeric", length = length(WestConA$Area))
for (i in 1:length(WestConA$Area)){
  adjWestConA[i] <- WestConA[i, ]$Area - background
}

WestConAAdj <- WestConA %>% mutate(adjAreaWest1 = adjWestConA)
View(WestConAAdj)
maybeWestConA <- WestConAAdj
maybeWestConA$adjAreaWest1[1] <- 0
View(maybeWestConA)

ConAEV <- maybeWestConA$adjAreaWest1[1:3]
ConAGsn <- maybeWestConA$adjAreaWest1[4:6]

shapiro.test(ConAEV) #p-value = 0.01774.
shapiro.test(ConAGsn) #p-value = 0.4608.
fConA <- var.test(ConAEV, ConAGsn, alternative = "two.sided")
fConA #F = 0.31588, num df = 2, denom df = 2, p-value = 0.4801

results <- t.test(ConAEV, ConAGsn, alternative = "two.sided", var.equal = TRUE)
results #t = -5.096, df = 4, p-value = 0.007002


nonparametric <- wilcox.test(ConAEV, ConAGsn)
nonparametric
#W = 0, p-value = 0.1.
```


```{r}
ConAshort <- read.csv("Actual Data/conA30kDa.csv")
View(ConAshort)
background <- ConAshort$Area[4]
background


ConAshort <- ConAshort[-4, ]

adjConAshort <- vector(mode = "numeric", length = length(ConAshort$Area))
for (i in 1:length(ConAshort$Area)){
  adjConAshort[i] <- ConAshort[i, ]$Area - background
}

ShortConAAdj <- WestConA %>% mutate(adjAreaWest1 = adjConAshort)
View(ShortConAAdj)

ShortConAAdj$adjAreaWest1[2] <- 0
ShortConAAdj

ConAEVshort <- ShortConAAdj$adjAreaWest1[1:3]
ConAGsnshort <- ShortConAAdj$adjAreaWest1[4:6]
shapiro.test(ConAEVshort) #p-value = 0.2455.
shapiro.test(ConAGsnshort)#p-value = 0.9803.
fvar <- var.test(ConAEVshort, ConAGsnshort, alternative = "two.sided")
fvar #p-value = 0.5899.F = 0.41837.
#All assumptions met!

tConAShort <- t.test(ConAEVshort, ConAGsnshort, alternative = "two.sided", var.equal = TRUE)
tConAShort #t = -8.8253, df = 4, p-value = 0.0009098.
```


```{r}
RCAIshort <- read.csv("Actual Data/RCAI25kDa.csv")
View(RCAIshort)
background <- RCAIshort$Area[4]
background
RCAIshort <- RCAIshort[-4, ]

adjRCAIshort <- vector(mode = "numeric", length = length(RCAIshort$Area))
for (i in 1:length(RCAIshort$Area)){
  adjRCAIshort[i] <- RCAIshort[i, ]$Area - background
}

ShortRCAIAdj <- RCAIshort %>% mutate(adjAreaWest1 = adjRCAIshort)
View(ShortRCAIAdj)
RCAIshortEV <- ShortRCAIAdj$adjAreaWest1[1:3]
RCAIshortGsn <- ShortRCAIAdj$adjAreaWest1[4:6]
shapiro.test(RCAIshortEV)
shapiro.test(RCAIshortGsn)
fRCAIshort <- var.test(RCAIshortEV, RCAIshortGsn, alternative = "two.sided")
fRCAIshort #F = 0.033359, num df = 2, denom df = 2, p-value = 0.06456.

tRCAIshort <- t.test(RCAIshortEV, RCAIshortGsn, alternative = "two.sided", var.equal = TRUE)
tRCAIshort #p-value = 0.1486. 
```
```{r}
#RCAI even shorter.#About 50kDa. 

RCAIshorter <- read.csv("Actual Data/RCAIveryshort.csv")
View(RCAIshorter)
background <- RCAIshorter$Area[4]
background
RCAIshorter <- RCAIshorter[-4, ]

adjRCAIshorter <- vector(mode = "numeric", length = length(RCAIshorter$Area))
for (i in 1:length(RCAIshorter$Area)){
  adjRCAIshorter[i] <- RCAIshorter[i, ]$Area - background
}

ShorterRCAIAdj <- RCAIshorter %>% mutate(adjAreaWest1 = adjRCAIshorter)
View(ShorterRCAIAdj)
RCAIshorterEV <- ShorterRCAIAdj$adjAreaWest1[1:3]
RCAIshorterGsn <- ShorterRCAIAdj$adjAreaWest1[4:6]
shapiro.test(RCAIshorterEV)
shapiro.test(RCAIshorterGsn)
fRCAIshorter <- var.test(RCAIshorterEV, RCAIshorterGsn, alternative = "two.sided")
fRCAIshorter

tRCAIshorter <- t.test(RCAIshorterEV, RCAIshorterGsn, alternative = "two.sided", var.equal = TRUE)
tRCAIshorter #t = -2.4768, df = 4, p-value = 0.06845.
```

